"""Human-authored semantics used by the source-derived API reference.

The implementation modules stay annotation-light for contest use.  Details
that cannot be recovered safely from the AST live here so the generated docs
and the website share one reviewable source of truth.
"""


MODULE_CAPABILITIES = {
    "algorithm/BasicAlgorithms.py": (
        "Fibonacci数・転倒数・LIS・0/1 knapsackなど、頻出する列アルゴリズムを使える。",
        "Mo's algorithm、ダブリング、座標圧縮、区間併合、二分探索を1ファイルから選べる。",
        "radix sort・quickselect・部分集合列挙など、Python標準処理では遅くなりやすい部分を置き換えられる。",
    ),
    "convolution/FormalPowerSeries.py": (
        "昇冪係数列で形式的冪級数の加減乗除・微分・積分を行える。",
        "逆数・対数・指数・冪・平方根を指定した次数まで計算できる。",
        "多項式除算、Taylor shift、合成などの高水準処理へそのまま渡せる係数列を返す。",
    ),
    "convolution/NTT.py": (
        "NTT可能な法の上で係数列を高速に畳み込める。",
        "順変換・逆変換を明示的に実行し、変換済み配列を再利用できる。",
        "法と原始根を指定して、標準設定以外のNTTも構築できる。",
    ),
    "data_structure/FenwickTree.py": (
        "1次元列の一点加算とprefix和・半開区間和を O(log N) で処理できる。",
        "区間加算・区間和、疎な添字空間、2次元矩形和の各Fenwick構造を選べる。",
        "累積和が目標値以上になる最初の位置を O(log N) で探索できる。",
    ),
    "data_structure/SegmentTree.py": (
        "任意の結合的演算で一点更新・半開区間集約を O(log N) で処理できる。",
        "遅延伝播版では区間更新と区間集約を同じ計算量で扱える。",
        "永続版では過去versionを壊さずに更新し、任意versionへ問い合わせできる。",
    ),
    "data_structure/UnionFind.py": (
        "要素の併合、同一連結成分判定、代表元と成分sizeの取得をほぼ定数時間で行える。",
        "連結成分数を保ちながら、辺追加だけの連結性問題を処理できる。",
    ),
    "data_structure/WaveletMatrix.py": (
        "静的な数列に対するk番目、順位、頻度、前後の値を対数時間で取得できる。",
        "位置の半開区間と値域を同時に指定した問い合わせを処理できる。",
        "圧縮版を使えば大きな整数座標を値の種類数に応じたbit幅で保持できる。",
    ),
    "graph/CSRGraph.py": (
        "辺をCSR形式の連続配列へ格納し、隣接listより省メモリに走査できる。",
        "Dijkstra・0-1 BFS・BFS・トポロジカル順序・連結成分をCSR上で直接計算できる。",
        "SCCとLowLinkもCSR表現のまま処理し、成分ID・橋・関節点を取得できる。",
    ),
    "graph/ShortestPath.py": (
        "BFS・0-1 BFS・Dijkstra・Bellman–Fordなどを入力グラフに合わせて選べる。",
        "最短距離だけでなく直前頂点も取得し、始点からの経路を復元できる。",
        "全点対最短路や負閉路を含む問題にも対応できる。",
    ),
    "graph/MaxFlow.py": (
        "容量付き有向グラフの最大流を計算できる。",
        "辺ごとの流量と残余容量を確認し、最小カット側の頂点集合を取得できる。",
    ),
    "math/Matrix.py": (
        "list of listsで表した行列の加減算・乗算・累乗を行える。",
        "行列式、逆行列、線形方程式を法上または通常の数値上で計算できる。",
    ),
    "optimization/Optimization.py": (
        "monotone minima、SMAWK、divide-and-conquer DP最適化を使える。",
        "ヒストグラム・二値行列の最大長方形を線形時間で求められる。",
        "黄金分割探索とConvex Hull Trickで1変数最適化を高速化できる。",
    ),
    "prime/Factorization.py": (
        "64bit整数の素数判定とPollard's rhoによる素因数分解を行える。",
        "素因数の重複列・指数表・約数列を用途に応じて取得できる。",
        "Eulerのφ関数とMöbius関数を素因数分解結果から計算できる。",
    ),
    "string/SuffixArray.py": (
        "文字列または整数列のsuffix arrayとLCP配列を構築できる。",
        "patternに一致するsuffixの範囲を二分探索し、出現位置を列挙できる。",
    ),
    "tree/HeavyLightDecomposition.py": (
        "木をheavy pathへ分解し、頂点path・辺pathを少数の半開区間へ変換できる。",
        "LCA、頂点間距離、k個先の頂点、部分木区間を取得できる。",
        "Segment Treeなどと組み合わせてpath query・subtree queryを処理できる。",
    ),
}


PURPOSE_BY_NAME = {
    "add_query": "半開区間の問い合わせを登録し、そのquery IDを返す。",
    "best": "現在の評価が最大の候補番号を返す。",
    "bfs_csr": "重みなしグラフでstartから各頂点までの最短辺数と直前頂点を求める。",
    "binomial": "二項係数 C(n, k) を計算する。",
    "circuit": "要素を加えたときに生じるmatroidの基本回路を返す。",
    "components": "現在の連結成分数を返す。",
    "connected_components_csr": "無向グラフを連結成分へ分け、各頂点の成分IDと頂点groupを返す。",
    "dijkstra_csr": "非負重みグラフでstartからの最短距離と経路復元用の直前頂点を求める。",
    "divisors": "正の約数を昇順で列挙する。",
    "euler_phi": "1以上number以下でnumberと互いに素な整数の個数を返す。",
    "factor_count": "各素因数の指数を数える。",
    "factor_count_pairs": "素因数と指数の組を素因数順に返す。",
    "factorial": "n!を指定した法で計算する。",
    "from_adjacency": "隣接listを検証し、同じ辺をCSR形式へ変換する。",
    "get_edge": "edge_idに対応する辺の両端頂点を返す。",
    "lower_string": "英小文字からなる指定長のランダム文字列を生成する。",
    "mobius": "整数numberに対するMöbius関数の値を返す。",
    "modular_power": "baseのexponent乗をmodulusで割った余りを返す。",
    "neighbors": "指定頂点から出る辺を (行き先, 重み, 辺ID) の順で列挙する。",
    "normalize": "保持中の候補を評価順に整理し、上位だけを残す。",
    "pairs": "matchingに含まれる左右頂点の組を列挙する。",
    "play": "次に試す候補を選び、その番号を返す。",
    "pollard_rho": "合成数numberの非自明な因数を1つ探す。",
    "prime_factors": "素因数を重複込みで昇順に列挙する。",
    "reward": "直前に選んだ候補へ観測した報酬を反映する。",
    "run": "登録済みの処理を実行し、入力順に結果を返す。",
    "same": "2要素が同じ連結成分に属するか判定する。",
    "scc_ids_csr": "強連結成分数と頂点ごとの成分IDをトポロジカル順で返す。",
    "strongly_connected_components_csr": "各頂点の強連結成分IDと成分ごとの頂点列を構築する。",
    "top_k": "現在の範囲で値が大きい順にk件の集計結果を返す。",
    "topological_sort_csr": "有向非巡回グラフの頂点をトポロジカル順に並べる。閉路があればNoneを返す。",
    "transpose": "全ての辺の向きを反転したCSRグラフを返す。",
    "zero_one_bfs_csr": "重みが0または1のグラフでstartからの最短距離と直前頂点を求める。",
    "ancestors": "指定頂点から重心分解木の祖先へ向かう経路情報を返す。",
    "binary_search_float": "判定条件が切り替わる実数境界を指定回数の二分探索で近似する。",
    "binary_search_int": "判定条件が切り替わる整数境界を二分探索する。",
    "bit_indices": "整数の2進表現で1になっているbit位置を昇順に列挙する。",
    "bucket_sort": "非負整数keyを使ってvaluesを安定sortした列を返す。",
    "bucket_sort_permutation": "非負整数keyを安定sortしたときの元の添字順を返す。",
    "component_size": "指定頂点が属する連結成分の頂点数を返す。",
    "coordinate_compress": "値の大小関係を保った0始まりの順位へ座標圧縮する。",
    "decimal_digit_count": "非負整数の10進桁数を返す。",
    "depth": "指定頂点の根からの深さを返す。",
    "ensure_permutation": "列が0からn-1までを1回ずつ含む置換か判定する。",
    "fibonacci": "index番目のFibonacci数を高速doublingで求める。",
    "index": "指定要素・頂点に対応する内部indexを返す。",
    "integer_partitions": "整数totalの分割を辞書式順序で列挙する。",
    "integer_partitions_up_to": "指定上限までの各整数分割を列挙する。",
    "inversion_count": "列の転倒数と座標圧縮した順位列を求める。",
    "knapsack_01": "各品物を高々1回選ぶ0/1 knapsackの到達可能状態を計算する。",
    "knapsack_01_max": "各品物を高々1回選ぶ0/1 knapsackの最大価値を求める。",
    "kth_element": "列を部分的に並べ替え、0始まりでk番目に小さい値を返す。",
    "kth_on_path": "2頂点間のpath上で始点からk個進んだ頂点を返す。",
    "merge_intervals": "重なる区間を併合し、互いに交わらない半開区間列を返す。",
    "num_vertices": "現在登録されている頂点数を返す。",
    "parent_edge_of": "指定頂点と親を結ぶ辺IDを返す。",
    "parent_of": "指定頂点の親頂点を返す。",
    "permute": "permutationに従ってvaluesを並べ替えた新しいlistを返す。",
    "permute_in_place": "permutationに従ってvalues自体を破壊的に並べ替える。",
    "radix_sort_nonnegative": "非負整数列をradix sortで昇順に並べる。",
    "submasks": "maskの部分maskを大きい順に列挙する。",
    "supermasks": "指定bit幅の範囲でmaskを含む上位maskを列挙する。",
    "tree_center": "木の直径に対する中心頂点を1個または2個返す。",
    "tree_centroid": "取り除いた後の各成分が元の半分以下になる重心を返す。",
}


ARGUMENT_DETAILS = {
    "adjacency": "各頂点の隣接辺を並べた隣接list",
    "arm_count": "選択肢（arm）の個数",
    "block_size": "1ブロックに含める要素数",
    "build": "初期化時に前処理まで実行するか",
    "build_dag": "強連結成分を縮約したDAGも構築するか",
    "check_nonnegative": "負の辺重みがないことを検査するか",
    "check_weights": "全ての辺重みが0または1か検査するか",
    "combine": "2つの集約値をまとめる二項関数",
    "duration": "探索を続ける秒数",
    "end_temperature": "焼きなまし終了時の温度",
    "exact": "近似を使わず厳密な条件で処理するか",
    "fill_frequency": "初期値を何個あるものとして数えるか",
    "fill_value": "未設定位置に入れる初期値",
    "hash_function": "候補を同一判定するためのhash関数",
    "include_left": "左端を結果に含めるか",
    "include_right": "右端を結果に含めるか",
    "increasing_slopes": "直線の傾きを昇順で追加するか",
    "initialize": "初期状態を作って返す関数",
    "insert": "要素を現在の状態へ追加する関数",
    "k": "選ぶ個数または0-indexedの順位",
    "lazy_identity": "遅延作用を何もしない値",
    "lexicographical": "頂点番号が小さい順を優先するか",
    "lower_bound": "探索対象とする値の下限",
    "max_iterations": "反復回数の上限。Noneなら時間だけで終了判定する",
    "minimum": "値の下限。Noneなら入力から決める",
    "output": "各queryの現在の答えを返す関数",
    "p": "操作する位置（0始まり）または、このAPIで使う法",
    "propose": "現在状態から次の候補状態と評価差を作る関数",
    "python_int_sum": "区間和をPythonの任意精度整数で保持するか",
    "return_argmax": "最大値に加えて選んだ添字も返すか",
    "return_argmin": "最小値に加えて選んだ添字も返すか",
    "rollback": "snapshotで保存した状態まで巻き戻す関数",
    "snapshot": "現在状態を保存し、巻き戻し位置を返す関数",
    "start_temperature": "焼きなまし開始時の温度",
    "state_max": "同時に保持する候補状態数",
    "update": "候補状態を1回更新し、状態と評価を返す関数",
    "with_distance": "頂点番号だけでなく距離も返すか",
    "zero_indexed": "頂点番号を0始まりで出力するか",
    "target_depth": "祖先として取得したい根からの深さ",
}


RETURN_DETAILS = {
    "bfs_csr": "tuple[list[int], list[int]] — 1つ目は各頂点までの辺数（未到達は-1）、2つ目は経路復元用の直前頂点（未設定は-1）",
    "bipartite_coloring_csr": "list[int] | None — 各頂点の色0/1。二部グラフでなければNone",
    "connected_components_csr": "tuple[list[int], list[list[int]]] — 1つ目は頂点ごとの成分ID、2つ目は各成分に属する頂点の列",
    "dijkstra_csr": "tuple[list[number], list[int]] — 1つ目は各頂点への最短距離（未到達はinf）、2つ目は経路復元用の直前頂点（未設定は-1）",
    "divisors": "list[int] — numberの正の約数を昇順に並べた列",
    "euler_phi": "int — 1以上number以下でnumberと互いに素な整数の個数",
    "factor_count": "dict[int, int] — keyは素因数、valueはその指数",
    "factor_count_pairs": "list[tuple[int, int]] — (素因数, 指数)を素因数の昇順に並べた列",
    "mobius": "int — numberのMöbius関数値（-1、0、1のいずれか）",
    "neighbors": "iterator[tuple[int, number, int]] — (行き先頂点, 辺重み, 元の辺ID)を辺ごとにyieldする",
    "pollard_rho": "int — numberの非自明な因数。numberが素数ならnumber自身",
    "prime_factors": "list[int] — 素因数を重複込みで昇順に並べた列",
    "scc_ids_csr": "tuple[int, list[int]] — 強連結成分数と、頂点ごとの成分ID",
    "strongly_connected_components_csr": "tuple[list[int], list[list[int]]] — 頂点ごとの成分IDと、各成分に属する頂点の列",
    "topological_sort_csr": "list[int] | None — 頂点のトポロジカル順。閉路があればNone",
    "zero_one_bfs_csr": "tuple[list[int], list[int]] — 1つ目は各頂点への最短距離（未到達はinf）、2つ目は経路復元用の直前頂点（未設定は-1）",
    "permute": "list[object] — permutationの順にvaluesの要素を並べた新しいlist",
    "permute_in_place": "list[object] — permutationの順へ並べ替えた入力valuesと同じobject",
    "tree_center": "list[int] — 木の中心頂点番号を昇順に並べた長さ1または2のlist",
    "tree_centroid": "list[int] — 木の重心頂点番号を昇順に並べた長さ1または2のlist",
}


# Big-O is kept separate from descriptive algorithm names.  These entries are
# used when the source alone cannot provide a useful per-API estimate.
COMPLEXITY_BY_MODULE = {
    "prime/Factorization.py": {
        "is_prime": "O(log N) 回の64bit mod乗算",
        "pollard_rho": "期待 O(sqrt(p))（pは最小の素因数）",
        "prime_factors": "期待 O(N^(1/4) log N)",
        "factor_count": "期待 O(N^(1/4) log N)",
        "divisors": "期待 O(N^(1/4) log N + tau(N))",
        "euler_phi": "期待 O(N^(1/4) log N)",
        "mobius": "期待 O(N^(1/4) log N)",
        "factor_count_pairs": "期待 O(N^(1/4) log N)",
    },
}
